### ISSUE TITLE
Add this to readme.txt

### ISSUE THREAD

**Issue by utsavbalhara** [The-Coder-Kishor/JEE-Main-Automatic-Calculator#2]
Dependencies
The following dependencies are required to run the program:

BeautifulSoup 4: A Python library for pulling data out of HTML and XML files.
To install BeautifulSoup, you can use the following command in the command prompt or terminal:

`pip install beautifulsoup4`

Note: You should already have pip installed on your system in order to run the above command. If you don't have pip installed, you can download it from [here](https://pip.pypa.io/en/stable/installation/).

**Comment by The-Coder-Kishor** [comment]
Thanks for the suggestion will add it now.

**Comment by The-Coder-Kishor** [comment]
Hope whatever you needed was done. You can reopen later if you want more changes to this.

**Comment by utsavbalhara** [comment]
bhai bhai, nice project.
